#!/usr/bin/env python3
"""
Script to prepare bivariate analysis data for the React website
Reads the CSV files generated by the notebook and creates JavaScript data files
"""

import pandas as pd
import numpy as np
import json

# Load the data
print("Loading data...")
df_daily = pd.read_csv('../outputs/df_clean_daily.csv')
district_summary = pd.read_csv('../outputs/district_summary.csv')
pincode_summary = pd.read_csv('../outputs/pincode_summary.csv')

print(f"✓ Daily data: {len(df_daily):,} records")
print(f"✓ District summary: {len(district_summary):,} records")
print(f"✓ Pincode summary: {len(pincode_summary):,} records")

# 1. Child vs Adult Scatter Data (sample 500 points from daily data)
print("\n1. Preparing scatter data...")
scatter_sample = df_daily.sample(n=500, random_state=42)
scatter_data = scatter_sample[['demo_age_17_', 'demo_age_5_17']].rename(
    columns={'demo_age_17_': 'adult', 'demo_age_5_17': 'child'}
).to_dict('records')

# 2. Child vs Adult Aggregated (by district)
print("2. Preparing aggregated district data...")
df_agg = df_daily.groupby(['state', 'district'])[['demo_age_5_17', 'demo_age_17_']].sum().reset_index()
agg_sample = df_agg.sample(n=min(100, len(df_agg)), random_state=42)
agg_data = agg_sample.rename(
    columns={'demo_age_17_': 'adult', 'demo_age_5_17': 'child'}
)[['district', 'adult', 'child']].to_dict('records')

# 3. Age Ratio Distribution (create bins)
print("3. Preparing age ratio distribution...")
df_daily['age_ratio'] = df_daily['demo_age_5_17'] / (df_daily['demo_age_17_'] + 1)
bins = np.arange(0, 1.05, 0.05)
hist, edges = np.histogram(df_daily['age_ratio'], bins=bins)
ratio_dist_data = [
    {'ratio': f"{edges[i]:.2f}", 'frequency': int(hist[i])}
    for i in range(len(hist))
]

# 4. Age Ratio by State (top 10 states)
print("4. Preparing state-level age ratios...")
top_states = df_daily.groupby('state')['demo_age_5_17'].sum().nlargest(10).index
df_top_states = df_daily[df_daily['state'].isin(top_states)]
state_ratios = df_top_states.groupby('state')['age_ratio'].agg(['mean', 'min', 'max']).reset_index()
state_data = state_ratios.to_dict('records')

# 5. Top 15 Districts by Total Updates
print("5. Preparing top districts by volume...")
top_districts_volume = district_summary.nlargest(15, 'total_updates')
districts_volume_data = top_districts_volume[['district', 'demo_age_5_17', 'demo_age_17_']].rename(
    columns={'demo_age_5_17': 'child', 'demo_age_17_': 'adult'}
).to_dict('records')

# 6. Top 15 Districts by Age Ratio
print("6. Preparing top districts by ratio...")
top_districts_ratio = district_summary.nlargest(15, 'age_ratio')
districts_ratio_data = top_districts_ratio[['district', 'age_ratio']].rename(
    columns={'age_ratio': 'ratio'}
).to_dict('records')

# 7. Pincode Concentration Curve
print("7. Preparing concentration curve...")
# Create 100 percentile points
percentile_points = []
for i in range(0, 101):
    idx = int(len(pincode_summary) * i / 100)
    if idx < len(pincode_summary):
        percentile_points.append({
            'percentile': i,
            'actual': float(pincode_summary.iloc[idx]['cumulative_share']),
            'perfect': i
        })

# 8. Volume vs Frequency
print("8. Preparing volume vs frequency...")
volume_freq_sample = pincode_summary.sample(n=300, random_state=42)
volume_freq_data = volume_freq_sample[['update_days', 'total_updates']].rename(
    columns={'update_days': 'days', 'total_updates': 'totalUpdates'}
).to_dict('records')

# 9. Top 20 Pincodes
print("9. Preparing top 20 pincodes...")
top_20_pincodes = pincode_summary.head(20)
top_20_data = top_20_pincodes[['pincode', 'total_updates']].rename(
    columns={'total_updates': 'totalUpdates'}
).to_dict('records')

# 10. Hexbin Joint Plot Data (Child vs Adult - sampled)
print("10. Preparing hexbin joint plot data...")
hexbin_sample = df_daily.sample(n=min(10000, len(df_daily)), random_state=42)
hexbin_data = hexbin_sample[['demo_age_17_', 'demo_age_5_17']].rename(
    columns={'demo_age_17_': 'adult', 'demo_age_5_17': 'child'}
).to_dict('records')

# 11. Age Ratio Box Plot Data
print("11. Preparing age ratio box plot data...")
ratio_stats = {
    'min': float(df_daily['age_ratio'].min()),
    'q1': float(df_daily['age_ratio'].quantile(0.25)),
    'median': float(df_daily['age_ratio'].median()),
    'q3': float(df_daily['age_ratio'].quantile(0.75)),
    'max': float(df_daily['age_ratio'].max()),
    'mean': float(df_daily['age_ratio'].mean())
}

# 12. Age Ratio Log Scale Distribution
print("12. Preparing age ratio log scale distribution...")
# Same bins as regular distribution, will be displayed with log scale on Y-axis
ratio_dist_log_data = ratio_dist_data.copy()

# 13. Child vs Adult at Pincode Level (Top 500)
print("13. Preparing pincode-level child vs adult data...")
top_500_pincodes = pincode_summary.head(500)
pincode_child_adult_data = top_500_pincodes[['pincode', 'adult_sum', 'child_sum']].rename(
    columns={'adult_sum': 'adult', 'child_sum': 'child'}
).to_dict('records')

# Calculate correlation
correlation = df_daily[['demo_age_5_17', 'demo_age_17_']].corr().iloc[0, 1]

# Calculate trend line coefficients
z = np.polyfit(df_daily['demo_age_17_'], df_daily['demo_age_5_17'], 1)

# Prepare statistics
stats = {
    'correlation': float(correlation),
    'trendSlope': float(z[0]),
    'trendIntercept': float(z[1]),
    'ageRatioStats': {
        'mean': float(df_daily['age_ratio'].mean()),
        'median': float(df_daily['age_ratio'].median()),
        'std': float(df_daily['age_ratio'].std()),
        'q25': float(df_daily['age_ratio'].quantile(0.25)),
        'q75': float(df_daily['age_ratio'].quantile(0.75))
    },
    'concentrationMetrics': {
        'top1pct': float(pincode_summary.iloc[:len(pincode_summary)//100]['update_share'].sum()),
        'top10pct': float(pincode_summary.iloc[:len(pincode_summary)//10]['update_share'].sum())
    }
}

# Compile all data
output_data = {
    'stats': stats,
    'scatterData': scatter_data,
    'aggregatedData': agg_data,
    'ratioDistribution': ratio_dist_data,
    'stateRatios': state_data,
    'topDistrictsVolume': districts_volume_data,
    'topDistrictsRatio': districts_ratio_data,
    'concentrationCurve': percentile_points,
    'volumeFrequency': volume_freq_data,
    'top20Pincodes': top_20_data,
    'hexbinData': hexbin_data,
    'ratioBoxPlot': ratio_stats,
    'ratioDistributionLog': ratio_dist_log_data,
    'pincodeChildAdult': pincode_child_adult_data
}

# Save to JSON file
output_path = '../website/src/data/bivariateData.json'
print(f"\nSaving to {output_path}...")
with open(output_path, 'w') as f:
    json.dump(output_data, f, indent=2)

print("✓ Data preparation complete!")
print(f"\nStatistics:")
print(f"  Correlation: {correlation:.4f}")
print(f"  Trend: y = {z[0]:.4f}x + {z[1]:.2f}")
print(f"  Mean age ratio: {df_daily['age_ratio'].mean():.4f}")
print(f"  Median age ratio: {df_daily['age_ratio'].median():.4f}")
print(f"  Top 1% concentration: {stats['concentrationMetrics']['top1pct']:.2f}%")
print(f"  Top 10% concentration: {stats['concentrationMetrics']['top10pct']:.2f}%")
